apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lwvxe350l-nodejs 
  janus-idp.io/tekton: lwvxe350l-nodejs
  backstage.io/kubernetes-id: lwvxe350l-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lwvxe350l-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml